# Live coding

## Zadanie 1.
Proszę utworzyć listę składającą się z liczb naturalnych od 1 do 12, następnie proszę usunąć jej pierwszy i ostatni element. Proszę odwrócić kolejność obciętej listy.

In [6]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [7]:
lista = lista[1:-1]
lista

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
# rozwiązanie ogólne
rev_list = []
for i in lista:
  rev_list = [i] + rev_list

rev_list

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2]

In [12]:
# rozwiązanie pythonowe
rev_list = lista[::-1]
rev_list

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2]

## Zadanie 2
Proszę utworzyć zbiór powiązanych ze sobą wartości zawierających nazwę zawodu z imieniem i nazwiskiem osoby wykonującej ten zawód. Następnie proszę przekształcając ten obiekt proszę utworzyć listy składające się z:
1. nazw zawodów;
2. imion i nazwisk;
3. samych imion:
4. samych nazwisk.

Dane:
1. Sherlock Holmes, detektyw;
2. Luke Skywalker, rycerz;
3. Jane Foster, fizyk;
4. Heinz Doofenshmirtz, naukowiec;
5. Peter Parker, dziennikarz;
6. Jennifer Walters, adwokat

In [13]:
collection = {'Sherlock Holmes': 'detektyw',
              'Luke Skywalker': 'rycerz',
              'Jane Foster': 'fizyk',
              'Heinz Doofenshmirtz': 'naukowiec',
              'Peter Parker': 'dziennikarz',
              'Jennifer Walters': 'adwokat'}

In [20]:
profesions = list(collection.values())
profesions

['detektyw', 'rycerz', 'fizyk', 'naukowiec', 'dziennikarz', 'adwokat']

In [15]:
names_surnames = list(collection.keys())
names_surnames

['Sherlock Holmes',
 'Luke Skywalker',
 'Jane Foster',
 'Heinz Doofenshmirtz',
 'Peter Parker',
 'Jennifer Walters']

In [17]:
only_names = [i[0].split(' ')[0] for i in collection.items()]
only_names

['Sherlock', 'Luke', 'Jane', 'Heinz', 'Peter', 'Jennifer']

In [18]:
only_surnames = [i[0].split(' ')[1] for i in collection.items()]
only_surnames

['Holmes', 'Skywalker', 'Foster', 'Doofenshmirtz', 'Parker', 'Walters']

## Zadanie 3
Proszę ponumerować zawody z poprzedniego zadania tworząc listę krotek.

In [21]:
numbered_profesions = []
for i in range(len(profesions)):
  numbered_profesions.append((i + 1, profesions[i]))

numbered_profesions

[(1, 'detektyw'),
 (2, 'rycerz'),
 (3, 'fizyk'),
 (4, 'naukowiec'),
 (5, 'dziennikarz'),
 (6, 'adwokat')]

## Zadanie 4
Proszę utworzyć obiekt nie zawierający porządku elementów składający się z imion z zadania drugiego. Proszę utworzyć listę zawierającą nazwiska z zadania drugiego w kolejności alfabetycznej.

In [22]:
unordered_names = set(only_names)
unordered_names

{'Heinz', 'Jane', 'Jennifer', 'Luke', 'Peter', 'Sherlock'}

In [23]:
alphabetical_ordered_surnames = sorted(only_surnames)
alphabetical_ordered_surnames

['Doofenshmirtz', 'Foster', 'Holmes', 'Parker', 'Skywalker', 'Walters']

## Zadanie 5
Z danych z zadania drugiego proszę utworzyć klasę, która przy tworzeniu obiektu jako argument przyjmuje słownik z danymi, a utworzony obiekt zawiera metodę:
1. zwracającą nazwiska w kolejności alfabetycznej;
2. ponumerowaną listę zawodów;
3. nieuporządkowane imiona;
4. zwracającą informacje o danych przechowywanych przez obiekt.

Obiekt ma zawierać przynajmniej trzy metody.

In [46]:
class profesions_class:
  def __init__(self, dict_arg):
    self.ans = dict_arg

  def sorted_names(self):
    self.result = sorted([i[0].split(' ')[1] for i in self.ans.items()])
    return self.result

  def numbered_profesions(self):
    self.result = []
    self.helper_list = list(self.ans.values())
    for i in range(len(self.helper_list)):
      self.result.append((i + 1, self.helper_list[i]))
    return self.result

  def unordered_names(self):
    self.helper_list = [i[0].split(' ')[0] for i in self.ans.items()]
    self.result = set(self.helper_list)
    return self.result

  def __str__(self):
    lines = []
    for name, job in self.ans.items():
      lines.append(f"imię i nazwisko: {name}\nzawód: {job}\n")
    return "\n".join(lines)


## Zadanie 6
Z danych z zadania drugiego proszę utworzyć obiekt przechowujący dane w ustrukturyzowanej formie składający się z trzech zmiennych:
1. imię;
2. nazwisko;
3. zawód.

Następnie proszę dodać kolumnę przechowującą rok powstania postaci zgodnie z poniższymi infomacjami:
1. Film "Thor" wszedł do kin w 2011 roku;
2. Pierwszy odcinek "Fineasza i Ferba" wyemitowano w 2007 roku;
3. Komiks "The Savage She-Hulk #1" trafił do sprzedaży w 1979;
4. "Nowa Nadzieja" miała premierę w 1977 roku;
5. Komiks "Amazing Fantasy #15" trafił do sprzedaży w 1962 roku;
6. "Studium w Szkarłacie" miało swoje pierwsze wydanie w 1887 roku.

Następnie w nowej kolumnie proszę obliczyć "wiek" postaci i posortować tabelę od najstarszych do najmłodszych postaci.

In [ ]:
collection = {'Sherlock Holmes': 'detektyw',
              'Luke Skywalker': 'rycerz',
              'Jane Foster': 'fizyk',
              'Heinz Doofenshmirtz': 'naukowiec',
              'Peter Parker': 'dziennikarz',
              'Jennifer Walters': 'adwokat'}

In [48]:
import pandas as pd

name = [i[0].split(' ')[0] for i in collection.items()]
surname = [i[0].split(' ')[0] for i in collection.items()]
profesion = list(collection.values())

data = {'name': name,
        'surname': surname,
        'profesion': profesion}

df = pd.DataFrame(data)
df

name   surname    profesion
0  Sherlock  Sherlock     detektyw
1      Luke      Luke       rycerz
2      Jane      Jane        fizyk
3     Heinz     Heinz    naukowiec
4     Peter     Peter  dziennikarz
5  Jennifer  Jennifer      adwokat

In [49]:
df['birth_year'] = [1887, 1977, 2011, 2007, 1962, 1979]
df

name   surname    profesion  birth_year
0  Sherlock  Sherlock     detektyw        1887
1      Luke      Luke       rycerz        1977
2      Jane      Jane        fizyk        2011
3     Heinz     Heinz    naukowiec        2007
4     Peter     Peter  dziennikarz        1962
5  Jennifer  Jennifer      adwokat        1979

In [50]:
df['age'] = 2025 - df['birth_year']
df

name   surname    profesion  birth_year  age
0  Sherlock  Sherlock     detektyw        1887  138
1      Luke      Luke       rycerz        1977   48
2      Jane      Jane        fizyk        2011   14
3     Heinz     Heinz    naukowiec        2007   18
4     Peter     Peter  dziennikarz        1962   63
5  Jennifer  Jennifer      adwokat        1979   46

In [53]:
df.sort_values(by = 'age', ascending=False)

name   surname    profesion  birth_year  age
0  Sherlock  Sherlock     detektyw        1887  138
4     Peter     Peter  dziennikarz        1962   63
1      Luke      Luke       rycerz        1977   48
5  Jennifer  Jennifer      adwokat        1979   46
3     Heinz     Heinz    naukowiec        2007   18
2      Jane      Jane        fizyk        2011   14

## Zadanie 7
Proszę dodać do siebe wektory (1, 2, 3, 4, 5, 6) i (0, 2, 0, 7, 1, 9) za pomocą standardowych operacji pythonowych oraz za pomocą pakietu Numpy.

In [54]:
# zwykły Python
vec1 = [1, 2, 3, 4, 5, 6]
vec2 = [0, 2, 0, 7, 1, 9]

sum_vec = [i + j for i, j in zip(vec1, vec2)]
sum_vec

[1, 4, 3, 11, 6, 15]

In [55]:
# Numpy
import numpy as np
vec1 = np.array([1, 2, 3, 4, 5, 6])
vec2 = np.array([0, 2, 0, 7, 1, 9])

vec1 + vec2

array([ 1,  4,  3, 11,  6, 15])

## Zadanie 8
Proszę wyznaczyć: **sumę**, **różnicę**, **iloczyn** i **iloraz** macierzy:

$$
A =
\begin{bmatrix}
1 & 4 \\
6 & 3
\end{bmatrix}
$$
oraz
$$
B =
\begin{bmatrix}
2 & 8 \\
7 & 0
\end{bmatrix}
$$

Przez **iloraz macierzy** $A$ i $B$ należy tutaj rozumieć **iloczyn macierzy $A$** i **macierzy odwrotnej do $B$**, czyli:

$$
A \cdot B^{-1}
$$


In [57]:
import numpy as np
A = np.array([[1, 4],
              [6, 3]])

B = np.array([[2, 8],
              [7, 0]])

In [58]:
A + B

array([[ 3, 12],
       [13,  3]])

In [59]:
A - B

array([[-1, -4],
       [-1,  3]])

In [60]:
A @ B

array([[30,  8],
       [33, 48]])

In [65]:
np.linalg.det(B) != 0

np.True_

In [63]:
A @ np.linalg.inv(B)

array([[0.5  , 0.   ],
       [0.375, 0.75 ]])

## Zadanie 9
Proszę wyznaczyć sumę, różnicę i iloczyn wszystkich par spośród liczb: 1, 7, 1, 0, 2, 0, 2, 5.

In [68]:
import numpy as np

numbers = np.array([1, 7, 1, 0, 2, 0, 2, 5])

numbers[:,None] + numbers[None,:]

array([[ 2,  8,  2,  1,  3,  1,  3,  6],
       [ 8, 14,  8,  7,  9,  7,  9, 12],
       [ 2,  8,  2,  1,  3,  1,  3,  6],
       [ 1,  7,  1,  0,  2,  0,  2,  5],
       [ 3,  9,  3,  2,  4,  2,  4,  7],
       [ 1,  7,  1,  0,  2,  0,  2,  5],
       [ 3,  9,  3,  2,  4,  2,  4,  7],
       [ 6, 12,  6,  5,  7,  5,  7, 10]])

In [70]:
np.triu(numbers[:,None] + numbers[None,:])

array([[ 2,  8,  2,  1,  3,  1,  3,  6],
       [ 0, 14,  8,  7,  9,  7,  9, 12],
       [ 0,  0,  2,  1,  3,  1,  3,  6],
       [ 0,  0,  0,  0,  2,  0,  2,  5],
       [ 0,  0,  0,  0,  4,  2,  4,  7],
       [ 0,  0,  0,  0,  0,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  0,  4,  7],
       [ 0,  0,  0,  0,  0,  0,  0, 10]])

In [72]:
numbers[:,None] - numbers[None,:]

array([[ 0, -6,  0,  1, -1,  1, -1, -4],
       [ 6,  0,  6,  7,  5,  7,  5,  2],
       [ 0, -6,  0,  1, -1,  1, -1, -4],
       [-1, -7, -1,  0, -2,  0, -2, -5],
       [ 1, -5,  1,  2,  0,  2,  0, -3],
       [-1, -7, -1,  0, -2,  0, -2, -5],
       [ 1, -5,  1,  2,  0,  2,  0, -3],
       [ 4, -2,  4,  5,  3,  5,  3,  0]])

In [69]:
numbers[:,None] * numbers[None,:]

array([[ 1,  7,  1,  0,  2,  0,  2,  5],
       [ 7, 49,  7,  0, 14,  0, 14, 35],
       [ 1,  7,  1,  0,  2,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 2, 14,  2,  0,  4,  0,  4, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 2, 14,  2,  0,  4,  0,  4, 10],
       [ 5, 35,  5,  0, 10,  0, 10, 25]])

In [71]:
np.triu(numbers[:,None] * numbers[None,:])

array([[ 1,  7,  1,  0,  2,  0,  2,  5],
       [ 0, 49,  7,  0, 14,  0, 14, 35],
       [ 0,  0,  1,  0,  2,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  4, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4, 10],
       [ 0,  0,  0,  0,  0,  0,  0, 25]])

## Zadanie 10
Proszę wyznaczyć iloraz wszystkich par spośród liczb: 1, 7, 1, 0, 2, 0, 2, 5.

In [84]:
import numpy as np

numbers = np.array([1, 7, 1, 0, 2, 0, 2, 5])

np.round(numbers[numbers > 0][:,None] / numbers[numbers > 0][None,:], decimals = 6)

array([[1.      , 0.142857, 1.      , 0.5     , 0.5     , 0.2     ],
       [7.      , 1.      , 7.      , 3.5     , 3.5     , 1.4     ],
       [1.      , 0.142857, 1.      , 0.5     , 0.5     , 0.2     ],
       [2.      , 0.285714, 2.      , 1.      , 1.      , 0.4     ],
       [2.      , 0.285714, 2.      , 1.      , 1.      , 0.4     ],
       [5.      , 0.714286, 5.      , 2.5     , 2.5     , 1.      ]])

## Zadanie 11
Proszę numerycznie obliczyć wartość całki funkcji $f(x) = x^2$ na przedziale $[0, 2]$.

In [89]:
import numpy as np
args = np.linspace(0, 2, 1000)
dx = np.array([2/1000]*len(args))
values = args**2

integral = np.sum(dx*values)
integral

np.float64(2.6680013346680016)

In [90]:
# rozwiązanie analityczne
(2**3)/3

2.6666666666666665

## Zadanie 12
Proszę numerucznie obliczyć wartość całki Darboux funkcji $f(x) = x^2$ na przedziale $[0,2]$ dla podziału $\Delta x = (0.1, 0.4, 0.5, 0.9, 1.2, 1.6, 1.9)$.

In [93]:
import numpy as np
args = [0.1, 0.4, 0.5, 0.9, 1.2, 1.6, 1.9]
delta_args = np.diff([0] + args)
values = np.array(args)**2

integral = np.sum(delta_args*values)
integral

np.float64(2.937)

## Zadanie 13
Proszę zdefiniować pythonową funkcję, która rozwiązuje równianie kwadratowe postaci $ax^2 + bx + c = 0$ bez używania Numpy.

In [99]:
def solve_quadratic(a, b, c):
    if a == 0 and b == 0 and c == 0:
        return "Nieskończenie wiele rozwiązań"
    if a == 0 and b != 0:
        return (-c/b, )
    if a == 0 and b == 0 and c != 0:
        return "Brak rozwiązań"
    delta = b**2 - 4*a*c
    if delta < 0:
        return "Brak rozwiązań rzeczywistych"
    sqrt_delta = delta**0.5
    if delta == 0:
        x0 = -b/(2*a)
        return (x0, )
    else:
        x1 = (-sqrt_delta-b)/(2*a)
        x2 = (sqrt_delta-b)/(2*a)
        if x1 < x2:
            return (x1, x2)
        else:
            return (x2, x1)

solve_quadratic(1, 1, -1)


(-1.618033988749895, 0.6180339887498949)

## Zadanie 14
Proszę zdefiniować pythonową funkcję, która dokonuje konwersji stopni Celsjusza na stopnie Farenheita.

In [ ]:
def celsius_to_fahrenheit(celsius):

    return (celsius * 9/5) + 32

# Zadanie 15
Proszę zdefiniować funkcję pythonową, która sprawdza czy dana liczba jest parzysta.

In [101]:
def check_odd_even(number):
    if not isinstance(number, int):
        raise TypeError
    elif number % 2 == 0:
        return f"Liczba {number} jest parzysta."
    else:
        return f"Liczba {number} jest nieparzysta."


check_odd_even(5)

'Liczba 5 jest nieparzysta.'

## Zadanie 16
Proszę zdefiniować funkcję pythonową, która oblicza pole trójkąta.

In [102]:
def calculate_triangle_area(base, height):
    if base < 0 or height < 0:
        raise ValueError
    else:
        return base*height/2


calculate_triangle_area(10, 5)

25.0

## Zadanie 17
Proszę zdefiniować funkcję pythonową, która odwraca kolejność pary uporządkowanej (krotki długości 2).

In [106]:
def swap_variables(pair):
  if not isinstance(pair, tuple):
    return ValueError
  return (pair[1], pair[0])

In [110]:
swap_variables((1, 2))

(2, 1)

In [108]:
swap_variables([1, 2])

ValueError

## Zadanie 18
Proszę zdefiniować pythonową funkcję, która sprawdza, czy podana liczba jest liczbą pierwszą.

In [111]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

is_prime(19)

True

In [112]:
is_prime(4)

False

## Zadanie 19
Proszę zdefiniować pythonową funkcję, która wypisuje wszystkie parzyste liczby pierwsze.

In [113]:
def all_even_primes():
  return 2

## Zadanie 20
Proszę zdefiniować pythonową funkcję, która zwraca znak liczby.

In [ ]:
def check_number(num):
    if num > 0:
        return 1
    elif num < 0:
        return -1
    else:
        return 0

## Zadanie 21
Proszę zdefiniować funkcję pythonową, która znajduje największą liczbę spośród trzech podanych.

In [ ]:
def find_largest(a, b, c):
    max_num = a
    if max_num < b:
        max_num = b
    if max_num < c:
        max_num = c
    return max_num

## Zadanie 22
Proszę zdefiniować funkcję pythonową, która oblicza sumę ciągu arytmetycznego.

In [ ]:
def first_last_n(first, last, n):
  return n*(first + last)/2

In [ ]:
def first_diff_n(first, diff, n):
  return n*(first + (n - 1)*r)/2

## Zadanie 23
Proszę zdefiniować funkcję pythonową, która oblicza sumę ciągu geometrycznego.

In [ ]:
def first_ratio_n(first, ratio, n):
  return first*(1 - ratio**n)/(1 - ratio)

## Zadanie 24
Proszę zdefiniować funkcję pythonową, która oblicza sumę szeregu geometrycznego.

In [ ]:
def geom_series(first, ratio):
  if abs(ratio) >= 1:
    return "Szereg jest rozbieżny."
  else:
    return first/(1 - ratio)